stages:
  - build

build_and_deploy:
  tags:
    - java10
    - maven
  stage: build
  only:
    - develop
    - master
  script:
    - bash ./change_version.sh
    - . ${CI_PROJECT_NAME}_version.env
    - echo "Changing version to "${P28_VERSION_STRING}
    - mvn versions:set -DnewVersion=${P28_VERSION_STRING}
    - mvn versions:commit
    - mvn clean deploy
  artifacts:
    paths:
      - target/${CI_PROJECT_NAME}-*.jar
